coverage:
  range: 60..100
  status:
    patch:
      default:
        target: 90%

codecov:
  ci:
    - "travis-ci.com"
    - "https://github.com/features/actions"
  notify:
    wait_for_ci: yes
    after_n_builds: 4
