pull_request_rules:
  - name: Request reviews from contributors
    conditions:
      - -draft
      - "review-requested!=@garage-contributors"
    actions:
      request_reviews:
        teams:
          - "@rlworkgroup/garage-contributors"
  - name: Merge queue for master
    conditions:
      - base=master
      - -conflict
      - "#approved-reviews-by>=2"
      - "approved-reviews-by=@maintainers"
      - "#changes-requested-reviews-by=0"
      - status-success="codecov/patch"
      - status-success="docs/readthedocs.org:garage"
      - status-success="Check pre-commit"
      - status-success="Normal Tests"
      - status-success="Large Tests"
      - status-success="MuJoCo-Based Tests"
      - status-success="Large MuJoCo-Based Tests"
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge queue for master (maintainers)
    conditions:
      - base=master
      - -conflict
      - "author=@rlworkgroup/maintainers"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success="Check pre-commit"
      - status-success="Normal Tests"
      - status-success="Large Tests"
      - status-success="MuJoCo-Based Tests"
      - status-success="Large MuJoCo-Based Tests"
      - status-success="codecov/patch"
      - status-success="docs/readthedocs.org:garage"
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge for master (docs only)
    conditions:
      - base=master
      - -conflict
      - "#approved-reviews-by>=2"
      - "approved-reviews-by=@maintainers"
      - "#changes-requested-reviews-by=0"
      - status-success="Check pre-commit"
      - status-success="docs/readthedocs.org:garage"
      - label=ready-to-merge
      - -files~=\.(?!md|rst|png|bib|html|css)
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge for master (docs only, maintainers)
    conditions:
      - base=master
      - -conflict
      - "author=@rlworkgroup/maintainers"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success="Check pre-commit"
      - status-success="docs/readthedocs.org:garage"
      - label=ready-to-merge
      - -files~=\.(?!md|rst|png|bib|html|css)
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge queue for release-2019.10
    conditions:
      - base=release-2019.10
      - -conflict
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success="Travis CI - Pull Request"
      - status-success="codecov/patch"
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge queue for release-2019.10 (automatic backports)
    conditions:
      - base=release-2019.10
      - head~=^mergify/bp/release-2019.10/pr.*
      - -conflict
      - "#changes-requested-reviews-by=0"
      - status-success="Travis CI - Pull Request"
      - status-success="codecov/patch"
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge queue for release-2020.06
    conditions:
      - base=release-2020.06
      - -conflict
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success="Travis CI - Pull Request"
      - status-success="codecov/patch"
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Merge queue for release-2020.06 (automatic backports)
    conditions:
      - base=release-2020.06
      - head~=^mergify/bp/release-2020.06/pr.*
      - -conflict
      - "#changes-requested-reviews-by=0"
      - status-success="Travis CI - Pull Request"
      - status-success="codecov/patch"
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Create backports for v2019.10
    conditions:
      - base=master
      - merged
      - label=backport-to-2019.10
    actions:
      backport:
        branches:
          - release-2019.10
  - name: Create backports for v2020.06
    conditions:
      - base=master
      - merged
      - label=backport-to-2020.06
    actions:
      backport:
        branches:
          - release-2020.06
