pull_request_rules:
  - name: Automatic merge queue for master
    conditions:
      - base=master
      - -conflict
      - "#approved-reviews-by>=2"
      - "approved-reviews-by=@maintainers"
      - "#changes-requested-reviews-by=0"
      - status-success=Travis CI - Pull Request
      - status-success=codecov/patch
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
  - name: Automatic merge queue for master (maintainers)
    conditions:
      - base=master
      - -conflict
      - author=@maintainers
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=Travis CI - Pull Request
      - status-success=codecov/patch
      - label=ready-to-merge
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      delete_head_branch: {}
