version: '2.2'
services:
  garage-base-nvidia:
    build:
      cache_from:
        - rlworkgroup/garage-nvidia:latest
      context: ../
      dockerfile: docker/Dockerfile.base.18.04
      args:
        - PARENT_IMAGE=nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04
    image: rlworkgroup/garage-base-nvidia
  garage-nvidia-no-files:
    build:
      cache_from:
        - rlworkgroup/garage-nvidia:latest
      context: ../
      dockerfile: docker/Dockerfile.nvidia
      args:
        - PARENT_IMAGE=rlworkgroup/garage-base-nvidia
    image: rlworkgroup/garage-nvidia-no-files
  garage-nvidia:
    build:
      cache_from:
        - rlworkgroup/garage-nvidia:latest
      context: ../
      dockerfile: docker/Dockerfile.runtime
      args:
        - PARENT_IMAGE=rlworkgroup/garage-nvidia-no-files
    image: ${TAG}
