# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Set up Python 3.6"
      uses: action/setup-python@v1
      with:
        python-version: 3.6
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
